### ISSUE TITLE
Header and Manifest in shell example

### ISSUE THREAD

**Issue by nikhilbchilwant** [acplt/openAAS#10]
With reference to shell example given at https://github.com/acplt/openAAS/tree/master/implementation, I have question about Header and Manifest, According to your page, `The Header provides information about the Shell and the Asset (Asset ID, Type Reference etc).` Then why does the `Header` tag in the example doesn't encapsulate `AASID` and `AssetID` tags? Second, in the shell example, what constitutes the Manifest? Third, what is difference between the Header and Manifest?

**Comment by FlorianPalm** [comment]
Hey,
> I have question about Header and Manifest, According to your page, The Header provides information about the Shell and the Asset (Asset ID, Type Reference etc). Then why does the Header tag in the example doesn't encapsulate AASID and AssetID tags

We have moved these attributes directly to the AssetAdministrationShell root object, so iterating over several AAS in order to find the correct one is less costly.

> Second, in the shell example, what constitutes the Manifest?

We have not implemented the manifest, as there is not really a common understanding what it should be used for.

Best Regards,
Florian
